export const TRADING_DATA_REQUEST = 'TRADING_DATA_REQUEST'
export const TRADING_DATA_SUCCESS = 'TRADING_DATA_SUCCESS'
export const TRADING_DATA_FAIL = 'TRADING_DATA_FAIL'


export const TRADING_CHART_REQUEST = 'TRADING_CHART_REQUEST'
export const TRADING_CHART_SUCCESS = 'TRADING_CHART_SUCCESS'
export const TRADING_CHART_FAIL = 'TRADING_CHART_FAIL'

export const WALLET_INFO_REQUEST = 'WALLET_INFO_REQUEST'
export const WALLET_INFO_SUCCESS = 'WALLET_INFO_SUCCESS'
export const WALLET_INFO_FAIL = 'WALLET_INFO_FAIL'

export const TRADING_START_REQUEST = 'TRADING_START_REQUEST'
export const TRADING_START_SUCCESS = 'TRADING_START_SUCCESS'
export const TRADING_START_FAIL = 'TRADING_START_FAIL'



