# Generated by Django 4.1.3 on 2024-01-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/lion_predator_animal.jpg', null=True, upload_to=''),
        ),
    ]
