# Generated by Django 3.2.14 on 2023-02-05 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotTestParams',
            fields=[
                ('assetPrecision', models.IntegerField(blank=True, null=True)),
                ('rsiPeriod', models.IntegerField(blank=True, null=True)),
                ('moveAvgFast', models.IntegerField(blank=True, null=True)),
                ('moveAvgSlow', models.IntegerField(blank=True, null=True)),
                ('rsiBuy', models.IntegerField(blank=True, null=True)),
                ('rsiSell', models.IntegerField(blank=True, null=True)),
                ('timeBuy', models.IntegerField(blank=True, null=True)),
                ('timeSell', models.IntegerField(blank=True, null=True)),
                ('marginSell', models.DecimalField(blank=True, decimal_places=3, max_digits=8)),
                ('percToSell', models.DecimalField(blank=True, decimal_places=3, max_digits=8)),
                ('capitalUnit', models.DecimalField(blank=True, decimal_places=3, max_digits=8)),
                ('initBalStable', models.DecimalField(blank=True, decimal_places=3, max_digits=8)),
                ('initBalAsset', models.DecimalField(blank=True, decimal_places=3, max_digits=8)),
                ('asset', models.CharField(blank=True, max_length=200)),
                ('stable', models.CharField(blank=True, max_length=200)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='bottestdata',
            name='balanceAssetBought',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='bottestdata',
            name='balanceAssetSold',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='bottestdata',
            name='bought',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='bottestdata',
            name='closeTime',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='bottestdata',
            name='high',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='bottestdata',
            name='low',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='bottestdata',
            name='open',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='bottestdata',
            name='openTime',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='bottestdata',
            name='rsiOne',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='bottestdata',
            name='rsiZero',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='bottestdata',
            name='sold',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='bottestdata',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='bottestdata',
            name='balanceAsset',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='bottestdata',
            name='idParams',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.bottestparams'),
        ),
    ]
