# Generated by Django 3.2.14 on 2023-02-25 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_bottestparams_timestamp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BotTestData',
            new_name='BotData',
        ),
        migrations.RenameModel(
            old_name='BotTestParams',
            new_name='BotParams',
        ),
    ]
