# Generated by Django 3.2.14 on 2023-02-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20230225_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='botdata',
            name='avgFast',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='botdata',
            name='avgSlow',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
